name: spinalhdl
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]

jobs:
  generate-hdl:
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # install oss fpga tools (to allow SpinalHDL simulate/formal to work)
    - name: install oss-cad-suite
      uses: YosysHQ/setup-oss-cad-suite@v3
      with:
          python-override: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: | 
        yosys --version
        iverilog -V
        cocotb-config --libpython
        cocotb-config --python-bin

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: sbt

    - name: 'SBT: compile +test'
      run: cd spinalhdl && sbt compile +test

    - name: 'SBT: Simulate'
      run: cd spinalhdl && sbt "runMain projectname.MyTopLevelSim"
    
    - name: 'SBT: Formal Verification'
      run: cd spinalhdl && sbt "runMain projectname.MyTopLevelFormal"
    
    - name: 'SBT: Generate Verilog'
      run: cd spinalhdl && sbt "runMain projectname.MyTopLevelVerilog"

    - name: 'SBT: Generate VHDL'
      run: cd spinalhdl && sbt "runMain projectname.MyTopLevelVhdl"

    - name: Copy to src
      shell: bash
      run: |
        echo "=== BEFORE:"
        ls -l src/
        echo "=== COPY:"
        find spinalhdl/hw/gen \( -name "*.v" -or -name "*.vhd*" \) -exec cp -av {} src/ \;
        echo "=== AFTER:"
        ls -l src/

    - name: Upload - prepare
      shell: bash
      run: |
        mkdir dist
        find spinalhdl/hw/gen \( -name "*.v" -or -name "*.vhd*" \) -exec cp -av {} dist/ \;
        find spinalhdl/simWorkspace \( -name "*.vcd" -or -name "*.fst" \) -exec cp -av {} dist/ \;

    - name: Upload - perform
      uses: actions/upload-artifact@v4
      with:
        name: spinalhdl-generated
        path: dist/
